### ISSUE TITLE
To use this library we need aleast live or current quotes of instruments or max websocket

### ISSUE THREAD

**Issue by ramakrishnamekala129** [dhan-oss/DhanHQ-py#1]

**Comment by ramakrishnamekala129** [comment]
Historical price is for conformation and live prices is for safety so please developer if not no one will able to make reliable algo system for themselves

**Comment by gkm2016** [comment]
Need Marketfeed API Asap

**Comment by dhan-oss** [comment]
Hello @RustAlgo @ramakrishnamekala129 

We have finally added Live Market Feed as part of v1.3. Do check it out and let us know your feedback. Closing this issue now.
