### ISSUE TITLE
ImportError: cannot import name 'marketfeed' from 'dhanhq' 

### ISSUE THREAD

**Issue by sudhakarsi** [dhan-oss/DhanHQ-py#14]
Attempting uninstall: dhanhq-ticker-py
    Found existing installation: dhanhq-ticker-py 0.1.0
    Uninstalling dhanhq-ticker-py-0.1.0:
      Successfully uninstalled dhanhq-ticker-py-0.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
breeze-historical-options 1.2 requires attrs==23.1.0, but you have attrs 23.2.0 which is incompatible.
breeze-historical-options 1.2 requires certifi==2023.11.17, but you have certifi 2024.2.2 which is incompatible.
breeze-historical-options 1.2 requires numpy==1.26.2, but you have numpy 1.26.4 which is incompatible.
breeze-historical-options 1.2 requires python-dotenv==1.0.0, but you have python-dotenv 1.0.1 which is incompatible.
breeze-historical-options 1.2 requires urllib3==2.1.0, but you have urllib3 2.2.0 which is incompatible.
yfinance 0.2.36 requires beautifulsoup4>=4.11.1, but you have beautifulsoup4 4.9.3 which is incompatible.
Successfully installed Brotli-1.1.0 TgCrypto-1.2.5 aiohttp-3.9.3 aiosignal-1.3.1 attrs-23.2.0 boltons-23.1.1 certifi-2024.2.2 charset-normalizer-3.3.2 dhanhq-ticker-py-0.1.0 docopt-0.6.2 environs-10.3.0 frozenlist-1.4.1 idna-3.6 marshmallow-3.20.2 msgpack-1.0.7 multidict-6.0.5 numpy-1.26.4 packaging
-23.2 polars-0.20.7 pycryptodome-3.20.0 python-dotenv-1.0.1 requests-2.31.0 scipy-1.12.0 setuptools-69.0.3 sourcedefender-11.0.10 urllib3-2.2.0 websockets-12.0 wheel-0.42.0 yarl-1.9.4

C:\Users\Sudhakar\Downloads>

C:\Users\Sudhakar\Downloads>
C:\Users\Sudhakar\Downloads>pip show dhanhq
Name: dhanhq
Version: 1.2.3
Summary: The official Python client for communicating with the Dhan API
Home-page:
Author: Dhan
Author-email: dhan-oss@dhan.co
License: MIT LICENSE
Location: C:\Users\Sudhakar\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: pandas, requests
Required-by:

Now tell what's wrong. Don't close issue till I close it else will open new again

**Comment by dhan-oss** [comment]
@sudhakarsi The version that you are using right now is dhanhq 1.2.3. We have added websockets as part of dhanhq 1.3. Kindly upgrade the library for the same.
You can do that with `pip install --upgrade dhanhq`

Also, `dhanhq-ticker-py` is not the official library of DhanHQ APIs. We recommend using official DhanHQ Library only.

**Comment by dhan-oss** [comment]
Closing this as no changes required in library itself.
