### ISSUE TITLE
Missing info in example given

### ISSUE THREAD

**Issue by sudhakarsi** [dhan-oss/DhanHQ-py#15]
There are tons of issues with DHAN library. I am picking from example only as of now

### Where to find security_id for NSE/BSE/MCX?

# Place an order for Equity Cash
dhan.place_order(security_id='1333',   #hdfcbank
    exchange_segment=dhan.NSE,
    transaction_type=dhan.BUY,
    quantity=10,
    order_type=dhan.MARKET,
    product_type=dhan.INTRA,
    price=0)
###  **how to get correlation id**
# Get order by correlation id
dhan.get_order_by_corelationID(corelationID)

dhan.intraday_minute_data(security_id,exchange_segment,instrument_type)

# Historical Daily Data
dhan.historical_daily_data(symbol,exchange_segment,instrument_type,expiry_code,from_date,to_date)

**How come JulianDate is here and what's its value?**

# Time Converter
dhan.convert_to_date_time(Julian Date)

**Comment by dhan-oss** [comment]
Hello @sudhakarsi 

Will look into adding more information here. Do note that this is just the hands-on code and not entire documentation for the library. You can refer to [API Documentation](https://dhanhq.co/docs/v1/) for all the information.

In case you feel there is some information which needs to be present here, feel free to contribute here, as it is an Open Source project.

**Comment by sudhakarsi** [comment]
Can you please pinpoint me where in documentation page above information is provided.

**Comment by dhan-oss** [comment]
Adding below:

> Where to find security_id for NSE/BSE/MCX?
<img width="596" alt="Screenshot 2024-02-13 at 5 33 44 PM" src="https://github.com/dhan-oss/DhanHQ-py/assets/112463199/bd0c0e19-23c3-4e53-b1a8-577875086809">

You can check the Security ID here: https://images.dhan.co/api-data/api-scrip-master.csv

> how to get correlation id
<img width="692" alt="Screenshot 2024-02-13 at 5 38 30 PM" src="https://github.com/dhan-oss/DhanHQ-py/assets/112463199/f76d54c5-8cec-47b1-84eb-7e654b941b44">

It is a unique identifier provided by you, also referred as 'tag'

> How come JulianDate is here and what's its value?
All the date formats in Historical Data API is sent as Julian Date. This is why time converter is provided.
