### ISSUE TITLE
market feed has issue in starting event_loop in constructor and security_id is expected as string while documented as integer value

### ISSUE THREAD

**Issue by megamobileapps** [dhan-oss/DhanHQ-py#16]
1. In marketfeed.py __init__ event_loop throws error so to fix that following needs to be done.
try:
            self.loop = asyncio.get_event_loop()
        except RuntimeError as e:
            if str(e).startswith('There is no current event loop in thread'):
                self.loop = asyncio.new_event_loop()
                asyncio.set_event_loop(self.loop)
            else:
                raise
2. inside     def create_subscription_packet(self, instruments, feed_request_code):
    security_id is being encoded but as it is a string value, so it thrws error.

**Comment by dhan-oss** [comment]
Hello @megamobileapps 

Since this is an OSS library, you can fix this issue yourself and raise a PR directly. In case you cannot, let us know, will add the fix.

**Comment by narenkram** [comment]
@megamobileapps I have same problem. Hey @dhan-oss Please add the fix, what are you waiting for?

**Comment by dhan-oss** [comment]
Have added comments here #28
