### ISSUE TITLE
Dhan Websockets does not have a function to add Instruments while the socket is running.

### ISSUE THREAD

**Issue by Pranav-Shinde** [dhan-oss/DhanHQ-py#17]
Everytime we have to add a few symbols to the existing websocket to fetch the LTP or quotes data, we have to disconnect the socket and then update the instruments list and then again start the websocket.

**Comment by dhan-oss** [comment]
Hello @Pranav-Shinde 

You can take a look at `subscribe_instruments` function, which includes this option.
