### ISSUE TITLE
Security id details (api-scrip-master)

### ISSUE THREAD

**Issue by hackalphatech** [dhan-oss/DhanHQ-py#2]
Add details in api-scrip-master

tradingsymbol         	name		expiry	       strike	 tick_size	  lot_size	   instrument_type

EURINR22DEC74.5CE	EURINR		28-12-2022	74.5	         0.0025	  1	           CE

NIFTY22D1518650PE	NIFTY		15-12-2022	18650	0.05	           50	           PE

**Comment by dhan-oss** [comment]
Hello @hackalphatech 

We have added details in API Scrip Master as raised by you and many other users. Kindly check now!
