### ISSUE TITLE
unsubscribe_symbols() not working in marketfeed

### ISSUE THREAD

**Issue by Spongy01** [dhan-oss/DhanHQ-py#21]
As mentioned in the title, the function to unsubscribe a symbol is not working in marketfeed api.
I want to add and remove symbols from my instrument list. Adding symbols works fine but unsubscribe_symbols() function throws error.

Inside this function, the call to self.create_subscription_packet() has an extra parameter 'subscribe' which is not in the function implementation.

![image](https://github.com/dhan-oss/DhanHQ-py/assets/78701247/92d14c0f-1b2a-4d4f-8698-06ca702da6fd)

how do I unsubscribe symbols ? without disconnecting and reconnecting the socket.

**Comment by dhan-oss** [comment]
Hello @Spongy01 

Noted this, will try to fix this in the next version of library. Meanwhile, if you are able to fix this and raise a PR, that will be great.

**Comment by Spongy01** [comment]
Yes, I would like to contribute,

Would you be able to provide a request frame structure as the documentation provided at https://dhanhq.co/docs/v1/live-market-feed/ only has the request for adding instruments, not removing.

**Comment by Spongy01** [comment]
I have updated the code, and the function call does not cause any errors but the stream data is not updated, if I unsubscribe or subscribe any instrument in the livestream, the changes are not reflected and the websocket only sends the instruments subscribed at the time of object creation.
