### ISSUE TITLE
intraday minute candle data not available 

### ISSUE THREAD

**Issue by rajsk2004** [dhan-oss/DhanHQ-py#22]
there is my code 
from dhanhq import dhanhq

acess_token =xxxxxxxx // security reason not showen here
cleint_id =xxxxxx // security reason not showen here
dhan = dhanhq(client_id,acess_token)
security_id='13'
exchange_segment='IDX_I'
instrument_type='INDEX'

intra=dhan.intraday_minute_data(security_id,exchange_segment,instrument_type)

print(intra)

output 

{'status': 'failure', 'remarks': {'error_code': 'RS-9005', 'message': 'Data not available'}, 'data': ''}

i also try with equity tcs same ouput showen

**Comment by dhan-oss** [comment]
Hello @rajsk2004 

Can you confirm when were you polling this API, as the intraday minute data is available only for current day, and is removed at day end.

**Comment by rajsk2004** [comment]
I try it after Market hour it's not working I have one more query about the
historical one minute data you have the function to fetch historical one
minute data but it's only provide the day candle I need the historical one
minute data for back testing my strategy kindly provide the historical one
minute data

**Comment by dhan-oss** [comment]
Currently we only have minute data for the current day, not on historical level. You can reach out to [help@dhan.co](mailto:help@dhan.co) for further queries.
