### ISSUE TITLE
Disconnected: Invalid Client ID

### ISSUE THREAD

**Issue by shubhamwankar** [dhan-oss/DhanHQ-py#23]
Hi Team,

I am facing an issue wherein my connection is being disconnected with the message Invalid Client ID. I am getting one or two valid responses but after that the connection is being disconnected.

I've tried finding the reason in the documentation but couldn't find any. Can you please help me out here?

Pasting the detailed message received below:

`RuntimeWarning: coroutine 'DhanFeed.connect' was never awaited
  self.connect()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n
Connected to websocket
Connected to websocket
Received: {'type': 'Market Depth', 'exchange_segment': 2, 'security_id': 41616, 'LTP': 248.0, 'depth': [{'bid_quantity': 300, 'ask_quantity': 195, 'bid_orders': 3, 'ask_orders': 1, 'bid_price': 247.8000030517578, 'ask_price': 248.3000030517578}, {'bid_quantity': 210, 'ask_quantity': 240, 'bid_orders': 4, 'ask_orders': 2, 'bid_price': 247.75, 'ask_price': 248.39999389648438}, {'bid_quantity': 570, 'ask_quantity': 1185, 'bid_orders': 8, 'ask_orders': 10, 'bid_price': 247.6999969482422, 'ask_price': 248.5}, {'bid_quantity': 90, 'ask_quantity': 15, 'bid_orders': 4, 'ask_orders': 1, 'bid_price': 247.64999389648438, 'ask_price': 248.5500030517578}, {'bid_quantity': 330, 'ask_quantity': 675, 'bid_orders': 3, 'ask_orders': 7, 'bid_price': 247.60000610351562, 'ask_price': 248.60000610351562}]}
Disconnected: Invalid Client ID
Received: None
Connection has been closed`

**Comment by dhan-oss** [comment]
Hello @shubhamwankar 

This is not a library issue, can you please raise it on official dhan support channel i.e. help@dhan.co.
