### ISSUE TITLE
Error while placing an order through API

### ISSUE THREAD

**Issue by Spongy01** [dhan-oss/DhanHQ-py#27]
I am trying to place orders using the dhanhq api but I am getting this error everytime:

`{'status': 'failure', 'remarks': {'error_code': 'RS-9005', 'message': 'Transactions Fails.'}, 'data': ''}`

Any leads on how to resolve these errors as I was not able to find any error code documentation which explained which error code meant what exactly.

**Comment by dhan-oss** [comment]
Hey @Spongy01 

Can you please add the data that you are adding inside the function? This error usually happens when the Security ID is invalid or quantity is not in multiple of lots.

Meanwhile, we are also updating error codes at our end.
