### ISSUE TITLE
AMO Orders are returning status 500, since amoTime is not managed properly!

### ISSUE THREAD

**Issue by jerinisready** [dhan-oss/DhanHQ-py#3]
When AMO's are placed, Dhan Expects `amoTime`, in the payload! But, Here in the line, instead of assigning 
`payload['amoTime'] = amo_time` the code type hints as `payload['amoTime']:amo_time`  

https://github.com/dhan-oss/DhanHQ-py/blob/e390751c4e19dbdea657418b5ff301c2d65bccba/dhanhq/dhanhq.py#L170-L172

If the issue is not fixed, The Entire Feature Will get Useless!

**Comment by dhan-oss** [comment]
Hello @jerinisready ,
We have resolved this issue in version 1.1.1
Please update the package and let us know the feedback.
Thank you for highlighting the issue.

**Comment by jerinisready** [comment]
> Hello @jerinisready , We have resolved this issue in version 1.1.1 Please update the package and let us know the feedback. Thank you for highlighting the issue.

Hi @dhan-oss, Raising a Concern as an open-source contributor;

- I have identified an Issue in your code base
- Fixed the Code
- Tested and Verified the Scenarios
- And then, put a PR in the proper way!

But unfortunately, my Contributions have been ignored, and Dhan Developers made the same changes! Making my contributions meaningless! 

In my shoes, it was a shameful activity, and it was not how a repo should have been managed!

**Comment by dhan-oss** [comment]
Hello @jerinisready,
We accept the mistake committed at our end. We would like to give you the due recognition for contributing to our Open Source project. Hence, we have reverted our last release and accepted your initial pull request. We have done course correction at our end and apologies for the mistake.
We are grateful for your contributions to this project and would like to have you as an active contributor moving forward as well.
