### ISSUE TITLE
While using market feed with 100 symbols 

### ISSUE THREAD

**Issue by Haeckerzz** [dhan-oss/DhanHQ-py#32]
When we call 
```
feed = marketfeed.DhanFeed(client_id, access_token, listofsymtosub)
feed .run_forever()
response = feed .get_data()
print(response)
```
here we get data fron single ticker at at a time now if I need to print ltp but I don't the correct ltp as there are 100 symbol

**Comment by dhan-oss** [comment]
Hello @Haeckerzz 

This will subscribe to all 100 instruments and you will get updated LTP for all instruments.
