### ISSUE TITLE
v2 SDK

### ISSUE THREAD

**Issue by williamzerner** [dhan-oss/DhanHQ-py#33]
The pypi hasnt been update to https://dhanhq.co/docs/v2/ version. Please fix that

**Comment by dhan-oss** [comment]
Hello @williamzerner 

Yes, we are already on it. It should be live here soon.

**Comment by dhan-oss** [comment]
Hello @williamzerner 

#34 We have made version 2 of DhanHQ Python Library live, do try it out.
