### ISSUE TITLE
AmoTime is missing PRE_OPEN

### ISSUE THREAD

**Issue by bailakare** [dhan-oss/DhanHQ-py#34]
AmoTime currently support only OPEN, OPEN_30, OPEN_60. PRE_OPEN is supported in web and is supported in v2. Please see amoTime in the link https://api.dhan.co/v2/#/operations/placeorder. However when using this package, it is still not supported. Please include support for PRE_OPEN.

**Comment by williamzerner** [comment]
v2 hasnt been updated here.

**Comment by dhan-oss** [comment]
Hello @williamzerner @bailakare 

Yes, this is pending. We will soon upgrade to v2 for entire Python library and you should be able to use all new features then.

**Comment by dhan-oss** [comment]
Hello @williamzerner @bailakare 

We have updated the library for DhanHQ v2. This is now available as part of the library. Do try it out and let us know your feedback.

[DhanHQ-py v2](https://github.com/dhan-oss/DhanHQ-py/releases/tag/2.0.0)
