### ISSUE TITLE
Only one tick per packet received.

### ISSUE THREAD

**Issue by roshi112** [dhan-oss/DhanHQ-py#35]
please do share, how many ticks we receive in single packet? like kite api’s websocket has around 600 to 1000 ticks data in single packet?

as I checked you guys provide only one tick per packet which is obviously going to be slow if you are options trader and will subscribe to large amount of tokens.

Brother the websocket data api is useless if you guys provide only 1 tick per packet received, as when you subscribe large amount of tokens you will not get synced prices or ltp or data and will get delayed data which will cause huge slipages.

I recently move back to dhan just because you guys start providing socket live feed api. I request you to provide at least 500 to 1000 ticks per packet (just like kite's websocket api provides) so that we can get synced prices.

**Comment by dhan-oss** [comment]
Hello @roshi112 

We have benchmarked our Live Market Feed with single tick per packet and found the results to be exceptionally good (with upto 5000 instruments on single socket).

We would humbly request you to kindly test the speed of Dhan Websocket at your end (for update in prices) and then let us know your feedback. Would be happy to hear you in case you face delay here.

**Comment by saurabhy7** [comment]
This only assumes speed for packet delivery. If someone wants to do some processing on packets where the number of instruments are as high as 5000. if there is no compression, alot cpu goes in processing a single packet only and lots of packets are lost. Could please process with some thing packet compression or multiple ticks delivered in single packet.

This is a bottle neck for large packet subscription. Could you please create some sort of feature for compression.

**Comment by dhan-oss** [comment]
@saurabhy7 

Right now, we are not looking to add compression as it will simply increase the compute time on both ends. To decide on the option of sending multiple tick in single packet, the approach with which the data is being parsed at Client can be debated upon.

In case your CPU times are going up, you need to relook at the parsing logic. Also, with increased processing time, it will not lose packets but create queue. As I said, both approaches do have it's pros and cons. To ensure lower latency from our end to deliver data to you, we are keeping it this way.
