### ISSUE TITLE
full packet mode not working and there is no callback functions

### ISSUE THREAD

**Issue by roshi112** [dhan-oss/DhanHQ-py#36]
# Assign default type 15 to tuples of size 2
processed_tuples = [ ]
for tup in tuples_list:
    if len(tup) == 2:
        processed_tuples.append((tup[0], tup[1], 15))
    else:
        processed_tuples.append(tup)

# Eliminate duplicate tuples
processed_tuples = list(set(processed_tuples))

# Separate tuples by type and prepare for batching
batches = defaultdict(list)
for tup in processed_tuples:
    exchange, instrument_id, type_ = tup
    batches[type_].append((exchange, instrument_id))

# Create the final dictionary with batches of the specified size
final_dict = {}
for type_ in [15, 17, 19, 21]:
    type_batches = [batches[type_][i:i+batch_size] for i in range(0, len(batches[type_]), batch_size)]
    final_dict[str(type_)] = type_batches

print(final_dict, "55555")
return final_dict

result: result= {‘15’: , ‘17’: , ‘19’: , ‘21’: [[(2, ‘44127’), (2, ‘54622’), (2, ‘47058’), (2, ‘47212’), (2, ‘47567’), (2, ‘50150’), (2, ‘59801’), (2, ‘47247’), (2, ‘36190’)]]}

no packet received with full packet and in the library marketfeed.py class dhanfeed func process_data there is no option to unpack full packet binary data

Note: I have checked it there is no binary packet received if subscribe for full packet(21)

**Comment by dhan-oss** [comment]
Hello @roshi112 

Over here, Full Packet is only available with Version 2 of APIs, where the structure of request has changed. We are updating the Python library to support Version 2 soon.

**Comment by dhan-oss** [comment]
Hello @roshi112 

We have updated the library for DhanHQ v2. Do try it out and let us know your feedback.

[DhanHQ-py v2](https://github.com/dhan-oss/DhanHQ-py/releases/tag/2.0.0)
