### ISSUE TITLE
Is it legal to use getDataS endpoint?

### ISSUE THREAD

**Issue by abhisheksoni27** [dhan-oss/DhanHQ-py#42]
ticks.dhan.co/getDataS

to get the seconds data OHLC values

**Comment by dhan-oss** [comment]
Hello @abhisheksoni27 

No, it is not. Although it is open right now, there soon will be auth enabled and it will disrupt your code and efforts will be wasted. Unless it is a documented API, available as part of DhanHQ, would rather ask you to refrain from using the endpoints as they may get changed depending on product changes.
